name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: download
      run: wget --output-document=affinity.zip https://drive.google.com/uc?id=14Mc9CwgHCTZ0ajYmYVbS5Av8dhayhzFR&export=download
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: affinity
        path: ${{github.workspace}}
